-- Needed for the "no double-booking" constraints (supported on RDS PostgreSQL)
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ---------- USERS ----------
CREATE TABLE users (
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    role        VARCHAR(10)  NOT NULL CHECK (role IN ('STUDENT', 'TEACHER')),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- lets other tables enforce "this FK must point to a TEACHER/STUDENT"
    CONSTRAINT uq_users_id_role UNIQUE (user_id, role)
);
CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email));

-- ---------- COURSES ----------
CREATE TABLE courses (
    course_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(150) NOT NULL,
    description  TEXT,
    subject      VARCHAR(80)  NOT NULL
);

-- ---------- CLASSROOMS ----------
CREATE TABLE classrooms (
    classroom_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number    INTEGER      NOT NULL UNIQUE,
    room_name      VARCHAR(100) NOT NULL,
    total_rows     SMALLINT     NOT NULL CHECK (total_rows > 0),
    total_columns  SMALLINT     NOT NULL CHECK (total_columns > 0),
    capacity       INTEGER GENERATED ALWAYS AS (total_rows * total_columns) STORED
);

-- ---------- CLASSES (SCHEDULE) ----------
CREATE TABLE classes (
    class_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     BIGINT      NOT NULL REFERENCES courses (course_id),
    teacher_id    BIGINT      NOT NULL,
    teacher_role  VARCHAR(10) NOT NULL DEFAULT 'TEACHER' CHECK (teacher_role = 'TEACHER'),
    classroom_id  BIGINT      NOT NULL REFERENCES classrooms (classroom_id),
    start_time    TIMESTAMPTZ NOT NULL,
    end_time      TIMESTAMPTZ NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'SCHEDULED' CHECK (status IN ('SCHEDULED', 'CANCELLED')),
    CONSTRAINT fk_classes_teacher
        FOREIGN KEY (teacher_id, teacher_role) REFERENCES users (user_id, role),
    CONSTRAINT chk_class_time CHECK (end_time > start_time),
    -- a room can't host two overlapping classes
    CONSTRAINT no_classroom_overlap
        EXCLUDE USING gist (classroom_id WITH =, tstzrange(start_time, end_time) WITH &&),
    -- a teacher can't be in two places at once
    CONSTRAINT no_teacher_overlap
        EXCLUDE USING gist (teacher_id WITH =, tstzrange(start_time, end_time) WITH &&)
);

-- ---------- ENROLLMENTS (student <-> course) ----------
CREATE TABLE enrollments (
    enrollment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     BIGINT      NOT NULL,
    student_role   VARCHAR(10) NOT NULL DEFAULT 'STUDENT' CHECK (student_role = 'STUDENT'),
    course_id      BIGINT      NOT NULL REFERENCES courses (course_id),
    enrolled_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_enrollments_student
        FOREIGN KEY (student_id, student_role) REFERENCES users (user_id, role),
    CONSTRAINT uq_enrollment UNIQUE (student_id, course_id)
);

-- Reject seats outside the room's row/column grid
CREATE OR REPLACE FUNCTION check_seat_within_room() RETURNS trigger AS $$
DECLARE
    v_rows SMALLINT;
    v_cols SMALLINT;
BEGIN
    SELECT cr.total_rows, cr.total_columns
      INTO v_rows, v_cols
      FROM classes cl
      JOIN classrooms cr ON cr.classroom_id = cl.classroom_id
     WHERE cl.class_id = NEW.class_id;

    IF NEW.seat_row > v_rows OR NEW.seat_col > v_cols THEN
        RAISE EXCEPTION 'Seat (%, %) is outside the room layout (% rows x % columns)',
            NEW.seat_row, NEW.seat_col, v_rows, v_cols
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;



-- Schedule lookups (date ranges, "what's on today")
CREATE INDEX idx_classes_start_time          ON classes (start_time);
-- Per-room and per-teacher schedules; the leading column also covers the FK
CREATE INDEX idx_classes_classroom_start     ON classes (classroom_id, start_time);
CREATE INDEX idx_classes_teacher_start       ON classes (teacher_id, start_time);
CREATE INDEX idx_classes_course_id           ON classes (course_id);

-- are already covered by their UNIQUE constraints)
CREATE INDEX idx_enrollments_course_id       ON enrollments (course_id);

-- Filtering users by role
CREATE INDEX idx_users_role                  ON users (role);


BEGIN;

-- Users: 5 teachers (1-5), 5 students (6-10)
INSERT INTO users (user_id, name, email, role) VALUES
(1,  'Anita Sharma',   'anita.sharma@coachingcenter.example',   'TEACHER'),
(2,  'Rahul Verma',    'rahul.verma@coachingcenter.example',    'TEACHER'),
(3,  'Meera Iyer',     'meera.iyer@coachingcenter.example',     'TEACHER'),
(4,  'Vikram Singh',   'vikram.singh@coachingcenter.example',   'TEACHER'),
(5,  'Priya Nair',     'priya.nair@coachingcenter.example',     'TEACHER'),
(6,  'Arjun Mehta',    'arjun.mehta@student.example',           'STUDENT'),
(7,  'Sneha Reddy',    'sneha.reddy@student.example',           'STUDENT'),
(8,  'Karan Patel',    'karan.patel@student.example',           'STUDENT'),
(9,  'Divya Menon',    'divya.menon@student.example',           'STUDENT'),
(10, 'Rohan Gupta',    'rohan.gupta@student.example',           'STUDENT');

-- Courses
INSERT INTO courses (course_id, title, description, subject) VALUES
(1, 'JEE Mathematics Foundation',  'Algebra, calculus and coordinate geometry for engineering entrance exams.', 'Mathematics'),
(2, 'NEET Physics Crash Course',   'Mechanics, optics and modern physics with timed problem practice.',          'Physics'),
(3, 'Organic Chemistry Essentials','Reaction mechanisms, named reactions and problem-solving techniques.',       'Chemistry');

-- Classrooms: varied layouts
INSERT INTO classrooms (classroom_id, room_number, room_name, total_rows, total_columns) VALUES
(1,  101, 'Newton Hall',        4,  6),
(2,  102, 'Curie Hall',         5,  8),
(3,  103, 'Tesla Studio',       3,  5),
(4,  104, 'Ramanujan Auditorium', 6, 10),
(5,  105, 'Faraday Room',       4,  4),
(6,  106, 'Bose Room',          5,  6),
(7,  107, 'Einstein Lecture Hall', 8, 10),
(8,  108, 'Kalam Studio',       3,  6),
(9,  109, 'Sarabhai Hall',      6,  8),
(10, 110, 'Seminar Room',       2,  6);

-- Classes: 4 days x 10 classes. Each day: 5 classes at 09:00-10:30 (rooms 101-105)
-- and 5 at 11:00-12:30 (rooms 106-110). One class per room per day.
INSERT INTO classes (class_id, course_id, teacher_id, classroom_id, start_time, end_time) VALUES
-- Day 1: 2026-10-05
(1,  1, 1, 1,  '2026-10-05 09:00', '2026-10-05 10:30'),
(2,  2, 2, 2,  '2026-10-05 09:00', '2026-10-05 10:30'),
(3,  3, 3, 3,  '2026-10-05 09:00', '2026-10-05 10:30'),
(4,  1, 4, 4,  '2026-10-05 09:00', '2026-10-05 10:30'),
(5,  2, 5, 5,  '2026-10-05 09:00', '2026-10-05 10:30'),
(6,  2, 2, 6,  '2026-10-05 11:00', '2026-10-05 12:30'),
(7,  3, 3, 7,  '2026-10-05 11:00', '2026-10-05 12:30'),
(8,  1, 4, 8,  '2026-10-05 11:00', '2026-10-05 12:30'),
(9,  2, 5, 9,  '2026-10-05 11:00', '2026-10-05 12:30'),
(10, 3, 1, 10, '2026-10-05 11:00', '2026-10-05 12:30'),
-- Day 2: 2026-10-06
(11, 2, 2, 1,  '2026-10-06 09:00', '2026-10-06 10:30'),
(12, 3, 3, 2,  '2026-10-06 09:00', '2026-10-06 10:30'),
(13, 1, 4, 3,  '2026-10-06 09:00', '2026-10-06 10:30'),
(14, 2, 5, 4,  '2026-10-06 09:00', '2026-10-06 10:30'),
(15, 3, 1, 5,  '2026-10-06 09:00', '2026-10-06 10:30'),
(16, 3, 3, 6,  '2026-10-06 11:00', '2026-10-06 12:30'),
(17, 1, 4, 7,  '2026-10-06 11:00', '2026-10-06 12:30'),
(18, 2, 5, 8,  '2026-10-06 11:00', '2026-10-06 12:30'),
(19, 3, 1, 9,  '2026-10-06 11:00', '2026-10-06 12:30'),
(20, 1, 2, 10, '2026-10-06 11:00', '2026-10-06 12:30'),
-- Day 3: 2026-10-07
(21, 3, 3, 1,  '2026-10-07 09:00', '2026-10-07 10:30'),
(22, 1, 4, 2,  '2026-10-07 09:00', '2026-10-07 10:30'),
(23, 2, 5, 3,  '2026-10-07 09:00', '2026-10-07 10:30'),
(24, 3, 1, 4,  '2026-10-07 09:00', '2026-10-07 10:30'),
(25, 1, 2, 5,  '2026-10-07 09:00', '2026-10-07 10:30'),
(26, 1, 4, 6,  '2026-10-07 11:00', '2026-10-07 12:30'),
(27, 2, 5, 7,  '2026-10-07 11:00', '2026-10-07 12:30'),
(28, 3, 1, 8,  '2026-10-07 11:00', '2026-10-07 12:30'),
(29, 1, 2, 9,  '2026-10-07 11:00', '2026-10-07 12:30'),
(30, 2, 3, 10, '2026-10-07 11:00', '2026-10-07 12:30'),
-- Day 4: 2026-10-08
(31, 1, 4, 1,  '2026-10-08 09:00', '2026-10-08 10:30'),
(32, 2, 5, 2,  '2026-10-08 09:00', '2026-10-08 10:30'),
(33, 3, 1, 3,  '2026-10-08 09:00', '2026-10-08 10:30'),
(34, 1, 2, 4,  '2026-10-08 09:00', '2026-10-08 10:30'),
(35, 2, 3, 5,  '2026-10-08 09:00', '2026-10-08 10:30'),
(36, 2, 5, 6,  '2026-10-08 11:00', '2026-10-08 12:30'),
(37, 3, 1, 7,  '2026-10-08 11:00', '2026-10-08 12:30'),
(38, 1, 2, 8,  '2026-10-08 11:00', '2026-10-08 12:30'),
(39, 2, 3, 9,  '2026-10-08 11:00', '2026-10-08 12:30'),
(40, 3, 4, 10, '2026-10-08 11:00', '2026-10-08 12:30');


-- Identity columns were given explicit IDs, so move the sequences past them
SELECT setval(pg_get_serial_sequence('users',      'user_id'),      (SELECT max(user_id)      FROM users));
SELECT setval(pg_get_serial_sequence('courses',    'course_id'),    (SELECT max(course_id)    FROM courses));
SELECT setval(pg_get_serial_sequence('classrooms', 'classroom_id'), (SELECT max(classroom_id) FROM classrooms));
SELECT setval(pg_get_serial_sequence('classes',    'class_id'),     (SELECT max(class_id)     FROM classes));

COMMIT;


CREATE SCHEMA IF NOT EXISTS coaching;

ALTER TABLE public.users       SET SCHEMA coaching;
ALTER TABLE public.courses     SET SCHEMA coaching;
ALTER TABLE public.classrooms  SET SCHEMA coaching;
ALTER TABLE public.classes     SET SCHEMA coaching;
ALTER TABLE public.enrollments SET SCHEMA coaching;


DROP TABLE IF EXISTS coaching.seat_bookings;   -- if you haven't already
DROP FUNCTION IF EXISTS public.check_seat_within_room();